### ISSUE TITLE
Errors on build with go version 1.17.2 darwin/arm64

### ISSUE THREAD

**Issue by jadefox10200** [jadefox10200/goprint#8]
When trying to download this package on a new machine to use it newly, I encountered the following errors due to changes in the syscall package. 

./main.go:13:12: undefined: syscall.MustLoadDLL
./main.go:143:28: undefined: syscall.StringToUTF16
./main.go:145:28: undefined: syscall.StringToUTF16
./main.go:180:27: undefined: syscall.UTF16PtrFromString
./main.go:280:26: undefined: syscall.UTF16PtrFromString
./main.go:308:26: undefined: syscall.UTF16PtrFromString
./main.go:661:23: undefined: syscall.StringToUTF16
./main.go:707:26: undefined: syscall.StringToUTF16
./out.go:11:16: undefined: syscall.NewLazyDLL
./out.go:39:36: undefined: syscall.Handle
./main.go:707:26: too many errors

**Comment by jadefox10200** [comment]
OPPS.
